/**
 * INsys Settings
 * Edit file ini langsung buat customize semua behavior, token, dan tampilan.
 * Token bisa diisi di sini (recommended) atau di-input manual saat runtime.
 *
 * GitHub Token  : https://github.com/settings/tokens
 *   -> Generate new token (classic), centang: repo, delete_repo, workflow
 * Vercel Token  : https://vercel.com/account/tokens
 *   -> Create Token, kasih nama, pilih expiry
 */

export const settings = {
  app: {
    name: "INsys",
    version: "1.0.0",
    description: "GitHub & Vercel Management CLI",
    author: "Walantaka Studio",
  },

  tokens: {
    github: process.env.GITHUB_TOKEN || "",
    vercel: process.env.VERCEL_TOKEN || "",
  },

  theme: {
    primary: "#FF6B00",
    secondary: "#FF9A3C",
    accent: "#FFD166",
    bg: "#0D0D0D",
    bgAlt: "#161616",
    border: "#2A2A2A",
    text: "#F0F0F0",
    textMuted: "#888888",
    success: "#00D26A",
    error: "#FF4444",
    warning: "#FFD166",
    info: "#4ECDC4",
    dim: "#374151",
    primaryDark: "#CC4400",
    muted: "#888888",
    white: "#F0F0F0",
  },

  layout: {
    divider: "─",
    cornerTL: "╭",
    cornerTR: "╮",
    cornerBL: "╰",
    cornerBR: "╯",
    vertical: "│",
    paddingX: 2,
    paddingY: 1,
  },

  ui: {
    boxStyle: "round",
    spinnerStyle: "dots",
    padding: 1,
    maxWidth: 120,
    minWidth: 60,
    lineChar: "─",
  },

  i18n: {
    defaultLang: "",
    available: ["en", "id", "ja"],
  },

  behavior: {
    confirmDestructive: true,
    showSystemInfo: true,
    animateHeader: true,
    clearOnStart: true,
    pageSize: 10,
    apiTimeout: 15000,
  },
};

export const i18n = {
  en: {
    selectLang: "Select your language",
    welcome: "Welcome to INsys",
    mainMenu: "Main Menu",
    github: "GitHub Manager",
    vercel: "Vercel Manager",
    settings: "Settings",
    exit: "Exit",
    enterGithubToken: "Enter your GitHub Personal Access Token:",
    enterVercelToken: "Enter your Vercel Token:",
    tokenSaved: "Token saved for this session.",
    tokenHint: "GitHub: github.com/settings/tokens  |  Vercel: vercel.com/account/tokens",
    loading: "Loading...",
    success: "Success",
    error: "Error",
    back: "← Back",
    create: "Create",
    delete: "Delete",
    list: "List",
    repos: "Repositories",
    projects: "Projects",
    deployments: "Deployments",
    createRepo: "Create Repository",
    deleteRepo: "Delete Repository",
    repoName: "Repository name:",
    repoDesc: "Description (optional):",
    repoPrivate: "Make private?",
    confirmDelete: "Are you sure you want to delete",
    yes: "Yes",
    no: "No",
    noRepos: "No repositories found.",
    noProjects: "No projects found.",
    noDeployments: "No deployments found.",
    createProject: "Create Project",
    deleteProject: "Delete Project",
    projectName: "Project name:",
    redeploy: "Redeploy",
    viewLogs: "View Logs",
    tokenMissing: "Token not found. Please enter it manually.",
    invalidToken: "Invalid token. Please check and try again.",
    sessionInfo: "Session Info",
    device: "Device",
    ip: "Local IP",
    os: "OS",
    started: "Session started",
    language: "Language",
    changeToken: "Change Tokens",
    changeLang: "Change Language",
    repoVisibility: "Visibility",
    public: "Public",
    private: "Private",
    stars: "Stars",
    forks: "Forks",
    updated: "Updated",
    status: "Status",
    ready: "READY",
    building: "BUILDING",
    failed: "ERROR",
    domain: "Domain",
    createdAt: "Created",
    framework: "Framework",
    repoCreated: "Repository created successfully!",
    repoDeleted: "Repository deleted successfully!",
    projectDeleted: "Project deleted successfully!",
    areYouSure: "This cannot be undone. Type the name to confirm:",
    mismatch: "Name mismatch. Cancelled.",
    githubUser: "GitHub User",
    vercelUser: "Vercel User",
    tokenStatus: "Token Status",
    active: "Active",
    notSet: "Not set",
    refresh: "Refresh",
    manageRepo: "Manage Repository",
    defaultBranch: "Default Branch",
    language_: "Language",
    cloneUrl: "Clone URL",
    manageProject: "Manage Project",
    latestDeployment: "Latest Deployment",
  },
  id: {
    selectLang: "Pilih bahasa kamu",
    welcome: "Selamat datang di INsys",
    mainMenu: "Menu Utama",
    github: "Manajer GitHub",
    vercel: "Manajer Vercel",
    settings: "Pengaturan",
    exit: "Keluar",
    enterGithubToken: "Masukkan GitHub Personal Access Token kamu:",
    enterVercelToken: "Masukkan Vercel Token kamu:",
    tokenSaved: "Token tersimpan untuk sesi ini.",
    tokenHint: "GitHub: github.com/settings/tokens  |  Vercel: vercel.com/account/tokens",
    loading: "Memuat...",
    success: "Berhasil",
    error: "Error",
    back: "← Kembali",
    create: "Buat",
    delete: "Hapus",
    list: "Daftar",
    repos: "Repositori",
    projects: "Proyek",
    deployments: "Deployment",
    createRepo: "Buat Repositori",
    deleteRepo: "Hapus Repositori",
    repoName: "Nama repositori:",
    repoDesc: "Deskripsi (opsional):",
    repoPrivate: "Jadikan privat?",
    confirmDelete: "Yakin ingin menghapus",
    yes: "Ya",
    no: "Tidak",
    noRepos: "Tidak ada repositori.",
    noProjects: "Tidak ada proyek.",
    noDeployments: "Tidak ada deployment.",
    createProject: "Buat Proyek",
    deleteProject: "Hapus Proyek",
    projectName: "Nama proyek:",
    redeploy: "Deploy Ulang",
    viewLogs: "Lihat Log",
    tokenMissing: "Token tidak ada. Masukkan manual.",
    invalidToken: "Token tidak valid. Cek dan coba lagi.",
    sessionInfo: "Info Sesi",
    device: "Perangkat",
    ip: "IP Lokal",
    os: "OS",
    started: "Sesi dimulai",
    language: "Bahasa",
    changeToken: "Ganti Token",
    changeLang: "Ganti Bahasa",
    repoVisibility: "Visibilitas",
    public: "Publik",
    private: "Privat",
    stars: "Bintang",
    forks: "Fork",
    updated: "Diperbarui",
    status: "Status",
    ready: "SIAP",
    building: "MEMBANGUN",
    failed: "GAGAL",
    domain: "Domain",
    createdAt: "Dibuat",
    framework: "Framework",
    repoCreated: "Repositori berhasil dibuat!",
    repoDeleted: "Repositori berhasil dihapus!",
    projectDeleted: "Proyek berhasil dihapus!",
    areYouSure: "Tidak bisa dibatalkan. Ketik nama untuk konfirmasi:",
    mismatch: "Nama tidak cocok. Dibatalkan.",
    githubUser: "Pengguna GitHub",
    vercelUser: "Pengguna Vercel",
    tokenStatus: "Status Token",
    active: "Aktif",
    notSet: "Belum diatur",
    refresh: "Refresh",
    manageRepo: "Kelola Repositori",
    defaultBranch: "Branch Utama",
    language_: "Bahasa",
    cloneUrl: "URL Clone",
    manageProject: "Kelola Proyek",
    latestDeployment: "Deployment Terakhir",
  },
  ja: {
    selectLang: "言語を選択してください",
    welcome: "INsysへようこそ",
    mainMenu: "メインメニュー",
    github: "GitHubマネージャー",
    vercel: "Vercelマネージャー",
    settings: "設定",
    exit: "終了",
    enterGithubToken: "GitHub Personal Access Tokenを入力:",
    enterVercelToken: "Vercel Tokenを入力:",
    tokenSaved: "トークンが保存されました。",
    tokenHint: "GitHub: github.com/settings/tokens  |  Vercel: vercel.com/account/tokens",
    loading: "読み込み中...",
    success: "成功",
    error: "エラー",
    back: "← 戻る",
    create: "作成",
    delete: "削除",
    list: "一覧",
    repos: "リポジトリ",
    projects: "プロジェクト",
    deployments: "デプロイメント",
    createRepo: "リポジトリを作成",
    deleteRepo: "リポジトリを削除",
    repoName: "リポジトリ名:",
    repoDesc: "説明（任意）:",
    repoPrivate: "プライベートにする？",
    confirmDelete: "削除しますか",
    yes: "はい",
    no: "いいえ",
    noRepos: "リポジトリが見つかりません。",
    noProjects: "プロジェクトが見つかりません。",
    noDeployments: "デプロイメントが見つかりません。",
    createProject: "プロジェクトを作成",
    deleteProject: "プロジェクトを削除",
    projectName: "プロジェクト名:",
    redeploy: "再デプロイ",
    viewLogs: "ログを表示",
    tokenMissing: "トークンが見つかりません。手動で入力してください。",
    invalidToken: "無効なトークンです。再確認してください。",
    sessionInfo: "セッション情報",
    device: "デバイス",
    ip: "ローカルIP",
    os: "OS",
    started: "開始時刻",
    language: "言語",
    changeToken: "トークンを変更",
    changeLang: "言語を変更",
    repoVisibility: "公開設定",
    public: "公開",
    private: "非公開",
    stars: "スター",
    forks: "フォーク",
    updated: "更新日",
    status: "ステータス",
    ready: "準備完了",
    building: "ビルド中",
    failed: "失敗",
    domain: "ドメイン",
    createdAt: "作成日",
    framework: "フレームワーク",
    repoCreated: "リポジトリが作成されました!",
    repoDeleted: "リポジトリが削除されました!",
    projectDeleted: "プロジェクトが削除されました!",
    areYouSure: "取り消せません。確認するために名前を入力:",
    mismatch: "名前が一致しません。キャンセルされました。",
    githubUser: "GitHubユーザー",
    vercelUser: "Vercelユーザー",
    tokenStatus: "トークン状態",
    active: "有効",
    notSet: "未設定",
    refresh: "更新",
    manageRepo: "リポジトリを管理",
    defaultBranch: "デフォルトブランチ",
    language_: "言語",
    cloneUrl: "クローンURL",
    manageProject: "プロジェクトを管理",
    latestDeployment: "最新デプロイ",
  },
};
