export const translations = {
  en: {
    welcome: "Welcome to INsys",
    tagline: "GitHub & Vercel Management CLI",
    selectLang: "Select your language",
    mainMenu: "Main Menu",
    github: "GitHub",
    vercel: "Vercel",
    settings: "Settings",
    exit: "Exit",
    back: "Back",
    confirm: "Confirm",
    cancel: "Cancel",
    success: "Success",
    error: "Error",
    loading: "Loading",
    noToken: "No token found. Enter manually.",
    tokenPromptGH: "Enter your GitHub Personal Access Token",
    tokenPromptVC: "Enter your Vercel API Token",
    tokenSaved: "Token saved for this session.",
    tokenHint: "Get GitHub token: https://github.com/settings/tokens",
    tokenHintVC: "Get Vercel token: https://vercel.com/account/tokens",
    repos: "Repositories",
    createRepo: "Create Repository",
    deleteRepo: "Delete Repository",
    listRepos: "List Repositories",
    repoName: "Repository name",
    repoDesc: "Description (optional)",
    repoPrivate: "Make private?",
    repoCreated: "Repository created successfully",
    repoDeleted: "Repository deleted",
    repoNamePrompt: "Enter repository name",
    projects: "Projects",
    createProject: "Create Project",
    deleteProject: "Delete Project",
    listProjects: "List Projects",
    deployments: "Deployments",
    listDeploys: "List Deployments",
    redeploy: "Redeploy",
    cancelDeploy: "Cancel Deployment",
    envVars: "Environment Variables",
    listEnv: "List Env Vars",
    addEnv: "Add Env Var",
    removeEnv: "Remove Env Var",
    envKey: "Key",
    envValue: "Value",
    envTarget: "Target (production/preview/development)",
    projectName: "Project name",
    confirmDelete: "Are you sure you want to delete",
    yes: "Yes",
    no: "No",
    sessionInfo: "Session Info",
    device: "Device",
    ip: "Local IP",
    started: "Session started",
    platform: "Platform",
    nodeVersion: "Node version",
    fetching: "Fetching data",
    done: "Done",
    noData: "No data found",
    apiError: "API Error",
    networkError: "Network error. Check your connection.",
    invalidToken: "Invalid or expired token.",
    domainList: "Domains",
    teamList: "Teams",
    changeToken: "Update Tokens",
    changeTheme: "Edit settings.js",
    viewSession: "View Session Info",
    copied: "Copied to clipboard",
    repoInitialized: "Repository initialized with README",
    openBrowser: "Opening in browser...",
    alias: "Aliases",
    listAlias: "List Aliases",
  },

  id: {
    welcome: "Selamat datang di INsys",
    tagline: "CLI Manajemen GitHub & Vercel",
    selectLang: "Pilih bahasa kamu",
    mainMenu: "Menu Utama",
    github: "GitHub",
    vercel: "Vercel",
    settings: "Pengaturan",
    exit: "Keluar",
    back: "Kembali",
    confirm: "Konfirmasi",
    cancel: "Batal",
    success: "Berhasil",
    error: "Error",
    loading: "Memuat",
    noToken: "Token tidak ditemukan. Masukkan manual.",
    tokenPromptGH: "Masukkan GitHub Personal Access Token kamu",
    tokenPromptVC: "Masukkan Vercel API Token kamu",
    tokenSaved: "Token disimpan untuk sesi ini.",
    tokenHint: "Ambil token GitHub: https://github.com/settings/tokens",
    tokenHintVC: "Ambil token Vercel: https://vercel.com/account/tokens",
    repos: "Repositori",
    createRepo: "Buat Repositori",
    deleteRepo: "Hapus Repositori",
    listRepos: "Daftar Repositori",
    repoName: "Nama repositori",
    repoDesc: "Deskripsi (opsional)",
    repoPrivate: "Jadikan privat?",
    repoCreated: "Repositori berhasil dibuat",
    repoDeleted: "Repositori dihapus",
    repoNamePrompt: "Masukkan nama repositori",
    projects: "Proyek",
    createProject: "Buat Proyek",
    deleteProject: "Hapus Proyek",
    listProjects: "Daftar Proyek",
    deployments: "Deployment",
    listDeploys: "Daftar Deployment",
    redeploy: "Redeploy",
    cancelDeploy: "Batalkan Deployment",
    envVars: "Variabel Lingkungan",
    listEnv: "Daftar Env Var",
    addEnv: "Tambah Env Var",
    removeEnv: "Hapus Env Var",
    envKey: "Kunci",
    envValue: "Nilai",
    envTarget: "Target (production/preview/development)",
    projectName: "Nama proyek",
    confirmDelete: "Kamu yakin mau hapus",
    yes: "Ya",
    no: "Tidak",
    sessionInfo: "Info Sesi",
    device: "Perangkat",
    ip: "IP Lokal",
    started: "Sesi dimulai",
    platform: "Platform",
    nodeVersion: "Versi Node",
    fetching: "Mengambil data",
    done: "Selesai",
    noData: "Data tidak ditemukan",
    apiError: "Error API",
    networkError: "Error jaringan. Cek koneksi kamu.",
    invalidToken: "Token tidak valid atau kedaluwarsa.",
    domainList: "Domain",
    teamList: "Tim",
    changeToken: "Update Token",
    changeTheme: "Edit settings.js",
    viewSession: "Lihat Info Sesi",
    copied: "Disalin",
    repoInitialized: "Repositori diinisialisasi dengan README",
    openBrowser: "Membuka di browser...",
    alias: "Alias",
    listAlias: "Daftar Alias",
  },

  ja: {
    welcome: "INsys へようこそ",
    tagline: "GitHub & Vercel 管理 CLI",
    selectLang: "言語を選択してください",
    mainMenu: "メインメニュー",
    github: "GitHub",
    vercel: "Vercel",
    settings: "設定",
    exit: "終了",
    back: "戻る",
    confirm: "確認",
    cancel: "キャンセル",
    success: "成功",
    error: "エラー",
    loading: "読み込み中",
    noToken: "トークンが見つかりません。手動で入力してください。",
    tokenPromptGH: "GitHub アクセストークンを入力",
    tokenPromptVC: "Vercel API トークンを入力",
    tokenSaved: "トークンをセッションに保存しました。",
    tokenHint: "GitHubトークン取得: https://github.com/settings/tokens",
    tokenHintVC: "Vercelトークン取得: https://vercel.com/account/tokens",
    repos: "リポジトリ",
    createRepo: "リポジトリ作成",
    deleteRepo: "リポジトリ削除",
    listRepos: "リポジトリ一覧",
    repoName: "リポジトリ名",
    repoDesc: "説明 (任意)",
    repoPrivate: "プライベートにする?",
    repoCreated: "リポジトリを作成しました",
    repoDeleted: "リポジトリを削除しました",
    repoNamePrompt: "リポジトリ名を入力",
    projects: "プロジェクト",
    createProject: "プロジェクト作成",
    deleteProject: "プロジェクト削除",
    listProjects: "プロジェクト一覧",
    deployments: "デプロイ",
    listDeploys: "デプロイ一覧",
    redeploy: "再デプロイ",
    cancelDeploy: "デプロイキャンセル",
    envVars: "環境変数",
    listEnv: "環境変数一覧",
    addEnv: "環境変数追加",
    removeEnv: "環境変数削除",
    envKey: "キー",
    envValue: "値",
    envTarget: "ターゲット (production/preview/development)",
    projectName: "プロジェクト名",
    confirmDelete: "本当に削除しますか",
    yes: "はい",
    no: "いいえ",
    sessionInfo: "セッション情報",
    device: "デバイス",
    ip: "ローカルIP",
    started: "セッション開始",
    platform: "プラットフォーム",
    nodeVersion: "Nodeバージョン",
    fetching: "データ取得中",
    done: "完了",
    noData: "データなし",
    apiError: "APIエラー",
    networkError: "ネットワークエラー。接続を確認してください。",
    invalidToken: "トークンが無効または期限切れです。",
    domainList: "ドメイン",
    teamList: "チーム",
    changeToken: "トークン更新",
    changeTheme: "settings.js 編集",
    viewSession: "セッション情報表示",
    copied: "コピーしました",
    repoInitialized: "READMEでリポジトリを初期化しました",
    openBrowser: "ブラウザで開いています...",
    alias: "エイリアス",
    listAlias: "エイリアス一覧",
  },
};

export function t(lang, key) {
  return translations[lang]?.[key] ?? translations["en"][key] ?? key;
}

